version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
        depends_on:
            - app
        container_name: helper_nginx


    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: helper_app


    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_NAME:-helper}
            - DB_USERNAME=${DB_USERNAME:-root}
            - DB_PASSWORD=${DB_PASSWORD:-root}
        command:  mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: helper_db

    adminer:
        image: adminer
        container_name: adminer-local
        restart: unless-stopped
        depends_on:
            - db
        environment:
            ADMINER_DEFAULT_SERVER: db
        ports:
            - "8080:8080"

